config/routes.rb
Rails.application.routes.draw do
  get 'pages/store' => 'pages#store'
  resources :bricks

end

app/models/brick.rb
class Brick < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bricks_controller.rb
class BricksController < ApplicationController
  before_action :set_brick, only: [:show, :edit, :update, :destroy]

  # GET /bricks
  # GET /bricks.json
  def index
    @bricks = Brick.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /bricks/1
  # GET /bricks/1.json
  def show
  end

  # GET /bricks/new
  def new
    @brick = Brick.new
  end

  # GET /bricks/1/edit
  def edit
  end

  # POST /bricks
  # POST /bricks.json
  def create
    @brick = Brick.new(brick_params)

    respond_to do |format|
      if @brick.save
        format.html { redirect_to @brick, notice: 'Brick was successfully created.' }
        format.json { render :show, status: :created, location: @brick }
      else
        format.html { render :new }
        format.json { render json: @brick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bricks/1
  # PATCH/PUT /bricks/1.json
  def update
    respond_to do |format|
      if @brick.update(brick_params)
        format.html { redirect_to @brick, notice: 'Brick was successfully updated.' }
        format.json { render :show, status: :ok, location: @brick }
      else
        format.html { render :edit }
        format.json { render json: @brick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bricks/1
  # DELETE /bricks/1.json
  def destroy
    @brick.destroy
    respond_to do |format|
      format.html { redirect_to bricks_url, notice: 'Brick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brick
      @brick = Brick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brick_params
      params.require(:brick).permit(:set_number, :name, :description, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout '_base'

  def store
    @bricks = Brick.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bricks_helper.rb
module BricksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bricks/_brick.html.erb
<div class="col-md-4">
    <div class="card card-product card-plain">
        <div class="image">
            <a href="#">
                <%= image_tag("#{brick.set_number}-1.jpg", alt: "...") %>
            </a>
        </div>
        <div class="content">
            <a href="#">
                <h4 class="title"><%= brick.name %></h4>
            </a>
            <p class="description">
               <%= brick.description %>
            </p>
            <div class="footer">
                <span class="price price-new"><%= brick.price %></span>
                <button class="btn btn-danger btn-simple pull-right" rel="tooltip" title="Remove from wishlist" data-placement="left">
                    <i class="fa fa-heart"></i>
                </button>
            </div>
        </div>
    </div> <!-- end card -->
 </div>

app/views/bricks/_form.html.erb
<%= form_for(@brick, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.form_group :set_number do |f| %>
      <%= f.label :set_number, class: 'col-md-2 control-label' %>
      <div class='col-md-10'>
        <%= f.number_field :set_number, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>
    <%= f.form_group :name do |f| %>
      <%= f.label :name, class: 'col-md-2 control-label' %>
      <div class='col-md-10'>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>
    <%= f.form_group :description do |f| %>
      <%= f.label :description, class: 'col-md-2 control-label' %>
      <div class='col-md-10'>
        <%= f.text_area :description, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>
    <%= f.form_group :price do |f| %>
      <%= f.label :price, class: 'col-md-2 control-label' %>
      <div class='col-md-10'>
        <%= f.text_field :price, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>
  </div>

  <div class="form-actions col-md-offset-2 col-md-10">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", bricks_path, class: 'btn' %>
  </div>
<% end %>

app/views/bricks/edit.html.erb
<% content_for :class, "scaffold" %>

<div class="page-header">
  <div class="container">
    <h2>Editing brick</h2>
  </div>
</div>

<div class="container">
  <%= render 'form' %>
</div>

app/views/bricks/index.html.erb
<% content_for :class, "scaffold" %>

<div class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h2>Listing bricks</h2>
      </div>
      <div class="col-xs-6">
        <%= link_to new_brick_path, class: 'btn btn-primary btn-large pull-right' do %>
        <%= fa_icon_tag "plus" %> Add Brick
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Set number</th>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th class="td-actions text-right">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @bricks.each do |brick| %>
        <tr>
          <td><%= brick.set_number %></td>
          <td><%= brick.name %></td>
          <td><%= brick.description %></td>
          <td><%= brick.price %></td>
          <td class="actions text-right">
            <%= link_to fa_icon_tag("eye"), brick, rel: 'tooltip', title: 'Show' %>
            <%= link_to fa_icon_tag("pencil"), edit_brick_path(brick), rel: 'tooltip', title: 'Edit' %>
            <%= link_to fa_icon_tag("trash-o"), brick, rel: 'tooltip', title: 'Delete',
            data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
        <% end %>
        <% if @bricks.length == 0 %>
        <tr><td colspan=42 class='text-center'>No bricks.</td></tr>
        <% end %>
      </tbody>
    </table>
  </div>

    <%= will_paginate @bricks, class: "pagination pagination-no-border" if @bricks.respond_to?(:total_pages) %>
  
  </div>

app/views/bricks/new.html.erb
<% content_for :class, "scaffold" %>

<div class="page-header">
  <div class="container">
    <h2>New brick</h2>
  </div>
</div>

<div class="container">
  <%= render 'form' %>
</div>

app/views/bricks/show.html.erb
<% content_for :class, "scaffold" %>

<div class="page-header">
  <div class="container">
    <h2>Showing brick</h2>
  </div>
</div>

<div class="container">
  <div class="form-horizontal">
    <div class="form-group">
      <label class="col-md-2 control-label">Set number</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.set_number %>
          </span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-2 control-label">Name</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.name %>
          </span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-2 control-label">Description</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.description %>
          </span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-2 control-label">Price</label>
      <div class="col-md-10">
        <div class="form-control">
          <span>
            <%= @brick.price %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-actions col-md-offset-2 col-md-10">
    <%= link_to fa_icon_tag("pencil") + ' Edit', edit_brick_path(@brick), class: 'btn btn-primary' %>
    <%= link_to 'Back', bricks_path, class: 'btn' %>
  </div>
</div>

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Get Shit Done Kit Pro by Creative Tim</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' %>

    <%= javascript_include_tag "//google-code-prettify.googlecode.com/svn/loader/run_prettify.js" %>
    <%= javascript_include_tag "//maps.googleapis.com/maps/api/js?sensor=false" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- If you are using TypeKit.com uncomment this code otherwise you can delete it -->
    <!--
    <script src="https://use.typekit.net/[your kit code here].js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    -->

    <%= favicon_link_tag "gsdk_pro/apple-icon.png", rel: "apple-touch-icon", type: "image/png", sizes: "76x76" %>
    <%= favicon_link_tag "gsdk_pro/favicon.png", rel: "icon", type: "image/png", sizes: "96x96" %>
    <%= yield :style %>
  </head>
  <body data-features="<%= yield :features %>" class="<%= yield :class %>">

    <%= yield %>

  </body>
</html>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-danger">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  </div>
<% end %>

<noscript>
  <div class="alert alert-danger">
    <div class="container">
      Please enable JavaScript on your browser for better experience.
    </div>
  </div>
</noscript>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <%= render "layouts/flashes" %>

  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GSDKit", "#", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "#" do %>
            <%= fa_icon_tag "user" %> Welcome, User
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<%= render :layout => "layouts/base" do %>
  <%= render "layouts/navbar" %>
  <%= yield %>
<% end %>

app/views/pages/store.html.erb
<% content_for :features, "ecommerce" %>
<% content_for :class, "ecommerce" %>

<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button id="menu-toggle" type="button" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar bar1"></span>
        <span class="icon-bar bar2"></span>
        <span class="icon-bar bar3"></span>
      </button>
      <a class="navbar-brand" href="http://gsdk.creative-tim.com"><i class="fa fa-chevron-left"></i> Back to Kit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse">
      <ul  class="nav navbar-nav navbar-right">
            <li>
                <a href="components.html">
                     All Components
                </a>
            </li>
            <li>
                <a href="home.html">
                     Home
                </a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     Blog
                     <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-with-icons">
                    <li>
                        <a href="blog-page.html">
                            <i class="pe-7s-comment"></i> Blog Page
                        </a>
                    </li>
                    <li>
                        <a href="blog-post.html">
                             <i class="pe-7s-news-paper"></i> Blog Post
                        </a>
                    </li>
                  </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Ecommerce
                     <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-with-icons">
                    <li>
                        <a href="ecommerce.html">
                             <i class="pe-7s-ticket"></i> Store Page
                        </a>
                    </li>
                    <li>
                        <a href="product-page.html">
                              <i class="pe-7s-piggy"></i> Product Page
                        </a>
                    </li>
                  </ul>
            </li>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    More
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu dropdown-with-icons">
                      <li>
                        <a href="contact-us.html">
                             <i class="pe-7s-mail-open-file"></i> Contact Us
                        </a>
                    </li>
                    <li>
                        <a href="about-us.html">
                            <i class="pe-7s-info"></i> About Us
                        </a>
                    </li>
                    <li>
                        <a href="pricing.html">
                            <i class="pe-7s-cash"></i> Pricing Page
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="pe-7s-gift"></i> More (soon)
                        </a>
                    </li>
                  </ul>
            </li>
            <li><a href="http://www.creative-tim.com/product/get-shit-done-pro" class="btn btn-round btn-default">Buy this Kit!</a></li>
       </ul>

    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="wrapper">
    <div class="parallax filter-black">
        <div class="parallax-image">
            <%= image_tag("brick-bg.jpg", alt: "...") %>
        </div>
        <div class="small-info">
            <h1>We <%= glyphicon_tag "heart" %> brick!</h1>
            <h3>25% Off and Free global delivery for all products</h3>
        </div>
    </div>

     <div class="section">
           <div class="container">
               <h2 class="section-title">Latest Offers</h2>
               <div class="row">
                <%= render @bricks %>
               </div>
           </div>
    </div><!-- section -->

    <div class="space-50"></div>
    <div class="subscribe-line subscribe-line-transparent" style="background-image: url('<%= asset_path("gsdk_pro/thumb.jpg") %>')">
        <div class="container">
            <div class="row">
                 <div class="col-md-9">
                    <form class="">
                         <div class="form-group">
                              <input type="text" value="" class="form-control" placeholder="Enter your email here...">
                         </div>
                     </form>
                 </div>
                 <div class="col-md-3">
                     <button type="button" class="btn btn-warning btn-fill btn-block">Subscribe Now!</button>
                 </div>
            </div>
         </div>
     </div>

    <footer class="footer footer-big footer-default">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                     <div class="form-group">
                        <select name="huge" class="selectpicker" data-style="btn-default btn-block" data-menu-style="dropdown-blue">

                          <option value="id">Bahasa Indonesia</option>
                          <option value="ms">Bahasa Melayu</option>
                          <option value="ca">Català</option>
                          <option value="da">Dansk</option>
                          <option value="de">Deutsch</option>
                          <option value="en" selected="">English</option>
                          <option value="es">Español</option>
                          <option value="el">Eλληνικά</option>
                          <option value="fr">Français</option>
                          <option value="it">Italiano</option>
                          <option value="hu">Magyar</option>
                          <option value="nl">Nederlands</option>
                          <option value="no">Norsk</option>
                          <option value="pl">Polski</option>
                          <option value="pt">Português</option>
                          <option value="fi">Suomi</option>
                          <option value="sv">Svenska</option>
                          <option value="tr">Türkçe</option>
                          <option value="is">Íslenska</option>
                          <option value="cs">Čeština</option>
                          <option value="ru">Русский</option>
                          <option value="th">ภาษาไทย</option>
                          <option value="zh">中文 (简体)</option>
                          <option value="zh-TW">中文 (繁體)</option>
                          <option value="ja">日本語</option>
                          <option value="ko">한국어</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <select name="huge" class="selectpicker" data-style="btn-default btn-block" data-menu-style="dropdown-blue">
                          <option value="ARS">ARS</option>
                          <option value="AUD">AUD</option>
                          <option value="BRL">BRL</option>
                          <option value="CAD">CAD</option>
                          <option value="CHF">CHF</option>
                          <option value="CNY">CNY</option>
                          <option value="CZK">CZK</option>
                          <option value="DKK">DKK</option>
                          <option value="EUR">EUR</option>
                          <option value="GBP">GBP</option>
                          <option value="HKD">HKD</option>
                          <option value="HUF">HUF</option>
                          <option value="IDR">IDR</option>
                          <option value="ILS">ILS</option>
                          <option value="INR">INR</option>
                          <option value="JPY">JPY</option>
                          <option value="KRW">KRW</option>
                          <option value="MYR">MYR</option>
                          <option value="MXN">MXN</option>
                          <option value="NOK">NOK</option>
                          <option value="NZD">NZD</option>
                          <option value="PHP">PHP</option>
                          <option value="PLN">PLN</option>
                          <option value="RUB">RUB</option>
                          <option value="SEK">SEK</option>
                          <option value="SGD">SGD</option>
                          <option value="TWD">TWD</option>
                          <option value="USD" selected="">USD</option>
                          <option value="VND">VND</option>
                          <option value="ZAR">ZAR</option>

                        </select>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1">
                    <h5 class="title">Company</h5>
                    <nav>
                        <ul>
                            <li>
                                <a href="#" >
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                   Find offers
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Discover Projects
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Our Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    About Us
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-3 col-md-offset-1">
                    <h5 class="title"> Help and Support</h5>
                    <nav>
                        <ul>
                            <li>
                                <a href="#">
                                   Contact Us
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                   How it works
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Terms & Conditions
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company Policy
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                   Money Back
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>

                <div class="col-md-3">
                    <h5 class="title">Latest News</h5>
                    <nav>
                        <ul>
                            <li>
                                <a href="#" >
                                   <i class="fa fa-twitter"></i> <b>Get Shit Done</b>
                                   The best kit in the market is here, just give it a try and let us...
                                   <hr class="hr-small">
                                </a>
                            </li>
                            <li>
                                  <a href="#" >
                                   <i class="fa fa-twitter"></i>
                                   We've just been featured on <b> Awwwards Website</b>! Thank you everybody for...
                                </a>
                            </li>

                        </ul>
                    </nav>
                </div>

            </div>
            <hr />
             <div class="social-area text-center">
                <h5>Join us on</h5>
                <a href="#" class="btn btn-social btn-round">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#"  class="btn btn-social btn-round">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#" class="btn btn-social btn-round">
                    <i class="fa fa-google-plus"></i>
                </a>
                <a href="#" class="btn btn-social btn-round">
                    <i class="fa fa-pinterest"></i>
                </a>
                <a href="#" class="btn btn-social btn-round">
                    <i class="fa fa-linkedin"></i>
                </a>
            </div>
            <div class="copyright">
                &copy; 2015 Creative Tim, made with love
            </div>
        </div>
    </footer>




</div> <!-- wrapper -->